name: docker
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIt_BRANCH=${{ github.ref_name }}
          push: false # TODO
