name: CI with all ignored tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: javac --version
      - run: java -XshowSettings -version
      - run: git grep -l ignore_TODO_ | xargs sed -i 's/ignore_TODO_//g'
      - run: mvn install -DskipTests=true
      - run: mvn install
      - if: success() || failure()
        uses: scacap/action-surefire-report@v1
